# Generated by Django 5.1.2 on 2024-10-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitcoinPrice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('open_time', models.DateTimeField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('trades', models.IntegerField()),
            ],
            options={
                'db_table': 'btcusdt',
            },
        ),
    ]
