# Generated by Django 5.1.2 on 2024-10-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitcoinprice',
            name='id',
        ),
        migrations.AlterField(
            model_name='bitcoinprice',
            name='open_time',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
    ]
