# Generated by Django 5.1.2 on 2024-10-17 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0002_remove_bitcoinprice_id_alter_bitcoinprice_open_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bitcoinprice',
            options={'managed': False},
        ),
    ]
